version: "3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - nodeserver

  nodeserver:
    build:
      context: ./node
    container_name: app
    restart: always
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: arm64v8/mysql:oracle
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    user: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
